eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: user-service
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      password: cZtx7b$xwkSL
      url: jdbc:mysql://localhost:3306/todo_calendar
      username: serviceaccount
  jpa:
      hibernate:
          ddl-auto: update