server:
  port: 9090

spring:
  application:
    name: auth-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

auth:
  jwt:
    secret: "${JWT_SECRET:e76f56a7a8a347962652f47dcc23f7e77718ba292da3fd6ed504d1eb4663da93}"
    expirationInMillis: "${JWT_EXPIRATION:1800000}"