eureka:
  client:
    healthcheck:
      enabled: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: car-service
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      password: cZtx7b$xwkSL
      url: jdbc:mysql://localhost:3306/todo_calendar
      username: serviceaccount
  jpa:
      database-platform: org.hibernate.dialect.MySQLDialect

auth:
  jwt:
    secret: "${JWT_SECRET:e76f56a7a8a347962652f47dcc23f7e77718ba292da3fd6ed504d1eb4663da93}"

server:
  port: 10090